// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nino.Core;

#nullable disable

namespace Nino.Core.Migrations
{
    [DbContext(typeof(NinoDbContext))]
    [Migration("20260327150018_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Nino.Domain.Entities.AniListResponse", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AniListCache");
                });

            modelBuilder.Entity("Nino.Domain.Entities.Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscordId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Channels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTimeOffset(new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -5, 0, 0, 0)),
                            DiscordId = "0"
                        });
                });

            modelBuilder.Entity("Nino.Domain.Entities.Configuration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("CongaPrefixType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Locale")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProgressPublishType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProgressResponseType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PublishPrivateProgress")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReleasePrefix")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId")
                        .IsUnique();

                    b.ToTable("Configuration");
                });

            modelBuilder.Entity("Nino.Domain.Entities.Episode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AirNotificationPosted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("Nino.Domain.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConfigurationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Nino.Domain.Entities.Observer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OriginGroupId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PrimaryRoleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReleaseChannelId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SecondaryRoleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TertiaryRoleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdateChannelId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("OriginGroupId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PrimaryRoleId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ReleaseChannelId");

                    b.HasIndex("SecondaryRoleId");

                    b.HasIndex("TertiaryRoleId");

                    b.HasIndex("UpdateChannelId");

                    b.ToTable("Observers");
                });

            modelBuilder.Entity("Nino.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("AirNotificationDelay")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AirNotificationRoleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AirNotificationUserId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AirNotificationsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AniListId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AniListOffset")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CongaParticipants")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("CongaReminderPeriod")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CongaRemindersEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DelegateObserverId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Motd")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectChannelId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReleaseChannelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UpdateChannelId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AirNotificationRoleId");

                    b.HasIndex("AirNotificationUserId");

                    b.HasIndex("DelegateObserverId");

                    b.HasIndex("GroupId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ProjectChannelId");

                    b.HasIndex("ReleaseChannelId");

                    b.HasIndex("UpdateChannelId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Nino.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscordId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Nino.Domain.Entities.State", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StateCache");
                });

            modelBuilder.Entity("Nino.Domain.Entities.Task", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssigneeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDone")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPseudo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastRemindedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Weight")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("EpisodeId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Nino.Domain.Entities.TemplateStaff", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssigneeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPseudo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Weight")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("ProjectId");

                    b.ToTable("TemplateStaff");
                });

            modelBuilder.Entity("Nino.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiscordId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Nino.Domain.Entities.Configuration", b =>
                {
                    b.HasOne("Nino.Domain.Entities.Group", null)
                        .WithOne("Configuration")
                        .HasForeignKey("Nino.Domain.Entities.Configuration", "GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Nino.Domain.Entities.Administrator", "Administrators", b1 =>
                        {
                            b1.Property<Guid>("ConfigurationId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("TEXT");

                            b1.HasKey("ConfigurationId", "Id");

                            b1.HasIndex("UserId");

                            b1.ToTable("Configuration_Administrators");

                            b1.WithOwner()
                                .HasForeignKey("ConfigurationId");

                            b1.HasOne("Nino.Domain.Entities.User", "User")
                                .WithMany()
                                .HasForeignKey("UserId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.Navigation("User");
                        });

                    b.Navigation("Administrators");
                });

            modelBuilder.Entity("Nino.Domain.Entities.Episode", b =>
                {
                    b.HasOne("Nino.Domain.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nino.Domain.Entities.Project", "Project")
                        .WithMany("Episodes")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Nino.Domain.Entities.Group", b =>
                {
                    b.HasOne("Nino.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Nino.Domain.Entities.Observer", b =>
                {
                    b.HasOne("Nino.Domain.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nino.Domain.Entities.Group", "OriginGroup")
                        .WithMany()
                        .HasForeignKey("OriginGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nino.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nino.Domain.Entities.Role", "PrimaryRole")
                        .WithMany()
                        .HasForeignKey("PrimaryRoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Nino.Domain.Entities.Project", "Project")
                        .WithMany("Observers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nino.Domain.Entities.Channel", "ReleaseChannel")
                        .WithMany()
                        .HasForeignKey("ReleaseChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nino.Domain.Entities.Role", "SecondaryRole")
                        .WithMany()
                        .HasForeignKey("SecondaryRoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Nino.Domain.Entities.Role", "TertiaryRole")
                        .WithMany()
                        .HasForeignKey("TertiaryRoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Nino.Domain.Entities.Channel", "UpdateChannel")
                        .WithMany()
                        .HasForeignKey("UpdateChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("OriginGroup");

                    b.Navigation("Owner");

                    b.Navigation("PrimaryRole");

                    b.Navigation("Project");

                    b.Navigation("ReleaseChannel");

                    b.Navigation("SecondaryRole");

                    b.Navigation("TertiaryRole");

                    b.Navigation("UpdateChannel");
                });

            modelBuilder.Entity("Nino.Domain.Entities.Project", b =>
                {
                    b.HasOne("Nino.Domain.Entities.Role", "AirNotificationRole")
                        .WithMany()
                        .HasForeignKey("AirNotificationRoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Nino.Domain.Entities.User", "AirNotificationUser")
                        .WithMany()
                        .HasForeignKey("AirNotificationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Nino.Domain.Entities.Observer", "DelegateObserver")
                        .WithMany()
                        .HasForeignKey("DelegateObserverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Nino.Domain.Entities.Group", "Group")
                        .WithMany("Projects")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nino.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nino.Domain.Entities.Channel", "ProjectChannel")
                        .WithMany()
                        .HasForeignKey("ProjectChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nino.Domain.Entities.Channel", "ReleaseChannel")
                        .WithMany()
                        .HasForeignKey("ReleaseChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nino.Domain.Entities.Channel", "UpdateChannel")
                        .WithMany()
                        .HasForeignKey("UpdateChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("Nino.Domain.Entities.Administrator", "Administrators", b1 =>
                        {
                            b1.Property<Guid>("ProjectId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("TEXT");

                            b1.HasKey("ProjectId", "Id");

                            b1.HasIndex("UserId");

                            b1.ToTable("Projects_Administrators");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId");

                            b1.HasOne("Nino.Domain.Entities.User", "User")
                                .WithMany()
                                .HasForeignKey("UserId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.Navigation("User");
                        });

                    b.OwnsMany("Nino.Domain.Entities.ProjectAlias", "Aliases", b1 =>
                        {
                            b1.Property<Guid>("ProjectId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("TEXT");

                            b1.HasKey("ProjectId", "Id");

                            b1.ToTable("Aliases", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ProjectId");
                        });

                    b.Navigation("Administrators");

                    b.Navigation("AirNotificationRole");

                    b.Navigation("AirNotificationUser");

                    b.Navigation("Aliases");

                    b.Navigation("DelegateObserver");

                    b.Navigation("Group");

                    b.Navigation("Owner");

                    b.Navigation("ProjectChannel");

                    b.Navigation("ReleaseChannel");

                    b.Navigation("UpdateChannel");
                });

            modelBuilder.Entity("Nino.Domain.Entities.Task", b =>
                {
                    b.HasOne("Nino.Domain.Entities.User", "Assignee")
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nino.Domain.Entities.Episode", "Episode")
                        .WithMany("Tasks")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignee");

                    b.Navigation("Episode");
                });

            modelBuilder.Entity("Nino.Domain.Entities.TemplateStaff", b =>
                {
                    b.HasOne("Nino.Domain.Entities.User", "Assignee")
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nino.Domain.Entities.Project", "Project")
                        .WithMany("TemplateStaff")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Assignee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Nino.Domain.Entities.Episode", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Nino.Domain.Entities.Group", b =>
                {
                    b.Navigation("Configuration")
                        .IsRequired();

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Nino.Domain.Entities.Project", b =>
                {
                    b.Navigation("Episodes");

                    b.Navigation("Observers");

                    b.Navigation("TemplateStaff");
                });
#pragma warning restore 612, 618
        }
    }
}
