// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nino.Core;

#nullable disable

namespace Nino.Core.Migrations
{
    [DbContext(typeof(NinoDbContext))]
    [Migration("20260309152930_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Nino.Domain.Entities.AniListResponse", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AniListCache");
                });

            modelBuilder.Entity("Nino.Domain.Entities.Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscordId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("Nino.Domain.Entities.Configuration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("CongaPrefix")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProgressPublishType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProgressResponseType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PublishPrivateProgress")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReleasePrefix")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId")
                        .IsUnique();

                    b.ToTable("Configuration");
                });

            modelBuilder.Entity("Nino.Domain.Entities.Episode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AirNotificationPosted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("Nino.Domain.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConfigurationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Nino.Domain.Entities.MentionRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscordId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MentionRoles");
                });

            modelBuilder.Entity("Nino.Domain.Entities.Observer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Blame")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OriginGroupId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProgressWebhook")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleasesWebhook")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("OriginGroupId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RoleId");

                    b.ToTable("Observers");
                });

            modelBuilder.Entity("Nino.Domain.Entities.PinchHitter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("UserId");

                    b.ToTable("PinchHitters");
                });

            modelBuilder.Entity("Nino.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("AirNotificationDelay")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AirNotificationEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("AirNotificationRoleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AirNotificationUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("AniListId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AniListOffset")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CongaParticipants")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("CongaReminderPeriod")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CongaRemindersEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Motd")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectChannelId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReleaseChannelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UpdateChannelId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AirNotificationRoleId");

                    b.HasIndex("AirNotificationUserId");

                    b.HasIndex("GroupId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ProjectChannelId");

                    b.HasIndex("ReleaseChannelId");

                    b.HasIndex("UpdateChannelId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Nino.Domain.Entities.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPseudo")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("Staff", t =>
                        {
                            t.HasCheckConstraint("CK_Staff_SingleOwner", "(ProjectId IS NULL) != (EpisodeId IS NULL)");
                        });
                });

            modelBuilder.Entity("Nino.Domain.Entities.State", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StateCache");
                });

            modelBuilder.Entity("Nino.Domain.Entities.Task", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDone")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastRemindedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Nino.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiscordId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Nino.Domain.Entities.Channel", b =>
                {
                    b.HasOne("Nino.Domain.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Nino.Domain.Entities.Configuration", b =>
                {
                    b.HasOne("Nino.Domain.Entities.Group", "Group")
                        .WithOne("Configuration")
                        .HasForeignKey("Nino.Domain.Entities.Configuration", "GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Nino.Domain.Entities.Administrator", "Administrators", b1 =>
                        {
                            b1.Property<Guid>("ConfigurationId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("TEXT");

                            b1.HasKey("ConfigurationId", "Id");

                            b1.HasIndex("UserId");

                            b1.ToTable("Configuration_Administrators");

                            b1.WithOwner()
                                .HasForeignKey("ConfigurationId");

                            b1.HasOne("Nino.Domain.Entities.User", "User")
                                .WithMany()
                                .HasForeignKey("UserId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.Navigation("User");
                        });

                    b.Navigation("Administrators");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Nino.Domain.Entities.Episode", b =>
                {
                    b.HasOne("Nino.Domain.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nino.Domain.Entities.Project", "Project")
                        .WithMany("Episodes")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Nino.Domain.Entities.Group", b =>
                {
                    b.HasOne("Nino.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Nino.Domain.Entities.Observer", b =>
                {
                    b.HasOne("Nino.Domain.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nino.Domain.Entities.Group", "OriginGroup")
                        .WithMany()
                        .HasForeignKey("OriginGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nino.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nino.Domain.Entities.Project", "Project")
                        .WithMany("Observers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nino.Domain.Entities.MentionRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.Navigation("Group");

                    b.Navigation("OriginGroup");

                    b.Navigation("Owner");

                    b.Navigation("Project");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Nino.Domain.Entities.PinchHitter", b =>
                {
                    b.HasOne("Nino.Domain.Entities.Episode", "Episode")
                        .WithMany("PinchHitters")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nino.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Episode");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nino.Domain.Entities.Project", b =>
                {
                    b.HasOne("Nino.Domain.Entities.MentionRole", "AirNotificationRole")
                        .WithMany()
                        .HasForeignKey("AirNotificationRoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Nino.Domain.Entities.User", "AirNotificationUser")
                        .WithMany()
                        .HasForeignKey("AirNotificationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Nino.Domain.Entities.Group", "Group")
                        .WithMany("Projects")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nino.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nino.Domain.Entities.Channel", "ProjectChannel")
                        .WithMany()
                        .HasForeignKey("ProjectChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nino.Domain.Entities.Channel", "ReleaseChannel")
                        .WithMany()
                        .HasForeignKey("ReleaseChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nino.Domain.Entities.Channel", "UpdateChannel")
                        .WithMany()
                        .HasForeignKey("UpdateChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("Nino.Domain.Entities.Alias", "Aliases", b1 =>
                        {
                            b1.Property<Guid>("ProjectId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("TEXT")
                                .UseCollation("NOCASE");

                            b1.HasKey("ProjectId", "Id");

                            b1.ToTable("Alias");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId");
                        });

                    b.OwnsMany("Nino.Domain.Entities.Administrator", "Administrators", b1 =>
                        {
                            b1.Property<Guid>("ProjectId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("TEXT");

                            b1.HasKey("ProjectId", "Id");

                            b1.HasIndex("UserId");

                            b1.ToTable("Projects_Administrators");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId");

                            b1.HasOne("Nino.Domain.Entities.User", "User")
                                .WithMany()
                                .HasForeignKey("UserId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.Navigation("User");
                        });

                    b.Navigation("Administrators");

                    b.Navigation("AirNotificationRole");

                    b.Navigation("AirNotificationUser");

                    b.Navigation("Aliases");

                    b.Navigation("Group");

                    b.Navigation("Owner");

                    b.Navigation("ProjectChannel");

                    b.Navigation("ReleaseChannel");

                    b.Navigation("UpdateChannel");
                });

            modelBuilder.Entity("Nino.Domain.Entities.Staff", b =>
                {
                    b.HasOne("Nino.Domain.Entities.Episode", "Episode")
                        .WithMany("AdditionalStaff")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Nino.Domain.Entities.Project", "Project")
                        .WithMany("KeyStaff")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Nino.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Nino.Domain.Entities.Role", "Role", b1 =>
                        {
                            b1.Property<Guid>("StaffId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Abbreviation")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Weight")
                                .HasColumnType("TEXT");

                            b1.HasKey("StaffId");

                            b1.ToTable("Staff");

                            b1.WithOwner()
                                .HasForeignKey("StaffId");
                        });

                    b.Navigation("Episode");

                    b.Navigation("Project");

                    b.Navigation("Role")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nino.Domain.Entities.Task", b =>
                {
                    b.HasOne("Nino.Domain.Entities.Episode", "Episode")
                        .WithMany("Tasks")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Episode");
                });

            modelBuilder.Entity("Nino.Domain.Entities.Episode", b =>
                {
                    b.Navigation("AdditionalStaff");

                    b.Navigation("PinchHitters");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Nino.Domain.Entities.Group", b =>
                {
                    b.Navigation("Configuration")
                        .IsRequired();

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Nino.Domain.Entities.Project", b =>
                {
                    b.Navigation("Episodes");

                    b.Navigation("KeyStaff");

                    b.Navigation("Observers");
                });
#pragma warning restore 612, 618
        }
    }
}
