// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nino.Core;

#nullable disable

namespace Nino.Core.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260225005613_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Nino.Core.Entities.AniListResponse", b =>
                {
                    b.Property<int>("AniListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("AniListId");

                    b.ToTable("AniListCache");
                });

            modelBuilder.Entity("Nino.Core.Entities.Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscordId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("Nino.Core.Entities.Episode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AirNotificationPosted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("Nino.Core.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscordId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Nino.Core.Entities.MentionRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("DiscordId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MentionRoles");
                });

            modelBuilder.Entity("Nino.Core.Entities.Observer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Blame")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OriginGroupId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProgressWebhook")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleasesWebhook")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("OriginGroupId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Observers");
                });

            modelBuilder.Entity("Nino.Core.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AirNotificationChannelId")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("AirNotificationDelay")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AirNotificationRoleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AirNotificationUserId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AirNotificationsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AniListId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AniListOffset")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CongaParticipants")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("CongaReminderPeriod")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CongaRemindersEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Motd")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectChannelId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReleaseChannelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UpdateChannelId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AirNotificationChannelId");

                    b.HasIndex("AirNotificationRoleId");

                    b.HasIndex("AirNotificationUserId");

                    b.HasIndex("GroupId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ProjectChannelId");

                    b.HasIndex("ReleaseChannelId");

                    b.HasIndex("UpdateChannelId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Nino.Core.Entities.State", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StateCache");
                });

            modelBuilder.Entity("Nino.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscordId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiscordId")
                        .IsUnique();

                    b.HasIndex("GroupId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Nino.Core.Entities.Episode", b =>
                {
                    b.HasOne("Nino.Core.Entities.Project", "Project")
                        .WithMany("Episodes")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Nino.Core.Entities.Staff", "AdditionalStaff", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("EpisodeId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("IsPseudo")
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("EpisodeId");

                            b1.HasIndex("UserId");

                            b1.ToTable("Episodes_AdditionalStaff");

                            b1.WithOwner()
                                .HasForeignKey("EpisodeId");

                            b1.HasOne("Nino.Core.Entities.User", "User")
                                .WithMany()
                                .HasForeignKey("UserId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.OwnsOne("Nino.Core.Entities.Role", "Role", b2 =>
                                {
                                    b2.Property<Guid>("StaffId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Abbreviation")
                                        .IsRequired()
                                        .HasMaxLength(16)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(32)
                                        .HasColumnType("TEXT");

                                    b2.Property<decimal>("Weight")
                                        .HasColumnType("TEXT");

                                    b2.HasKey("StaffId");

                                    b2.ToTable("Episodes_AdditionalStaff");

                                    b2.WithOwner()
                                        .HasForeignKey("StaffId");
                                });

                            b1.Navigation("Role")
                                .IsRequired();

                            b1.Navigation("User");
                        });

                    b.OwnsMany("Nino.Core.Entities.PinchHitter", "PinchHitters", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Abbreviation")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("EpisodeId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("EpisodeId");

                            b1.HasIndex("UserId");

                            b1.ToTable("PinchHitter");

                            b1.WithOwner()
                                .HasForeignKey("EpisodeId");

                            b1.HasOne("Nino.Core.Entities.User", "User")
                                .WithMany()
                                .HasForeignKey("UserId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.Navigation("User");
                        });

                    b.OwnsMany("Nino.Core.Entities.Task", "Tasks", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Abbreviation")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("EpisodeId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("IsDone")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTimeOffset?>("LastRemindedAt")
                                .HasColumnType("TEXT");

                            b1.Property<DateTimeOffset?>("UpdatedAt")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("EpisodeId");

                            b1.ToTable("Task");

                            b1.WithOwner()
                                .HasForeignKey("EpisodeId");
                        });

                    b.Navigation("AdditionalStaff");

                    b.Navigation("PinchHitters");

                    b.Navigation("Project");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Nino.Core.Entities.Group", b =>
                {
                    b.HasOne("Nino.Core.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");

                    b.OwnsOne("Nino.Core.Entities.Configuration", "Configuration", b1 =>
                        {
                            b1.Property<Guid>("GroupId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("CongaPrefix")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Locale")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("ProgressPublishType")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("ProgressResponseType")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("PublishPrivateProgress")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ReleasePrefix")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT");

                            b1.HasKey("GroupId");

                            b1.ToTable("Groups");

                            b1.WithOwner()
                                .HasForeignKey("GroupId");

                            b1.OwnsMany("Nino.Core.Entities.Administrator", "Administrators", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid>("GroupId")
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid>("UserId")
                                        .HasColumnType("TEXT");

                                    b2.HasKey("Id");

                                    b2.HasIndex("GroupId");

                                    b2.HasIndex("UserId");

                                    b2.ToTable("Groups_Administrators");

                                    b2.WithOwner()
                                        .HasForeignKey("GroupId");

                                    b2.HasOne("Nino.Core.Entities.User", "User")
                                        .WithMany()
                                        .HasForeignKey("UserId")
                                        .OnDelete(DeleteBehavior.Cascade)
                                        .IsRequired();

                                    b2.Navigation("User");
                                });

                            b1.Navigation("Administrators");
                        });

                    b.Navigation("Configuration")
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Nino.Core.Entities.Observer", b =>
                {
                    b.HasOne("Nino.Core.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nino.Core.Entities.Group", "OriginGroup")
                        .WithMany()
                        .HasForeignKey("OriginGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nino.Core.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nino.Core.Entities.Project", "Project")
                        .WithMany("Observers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("OriginGroup");

                    b.Navigation("Owner");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Nino.Core.Entities.Project", b =>
                {
                    b.HasOne("Nino.Core.Entities.Channel", "AirNotificationChannel")
                        .WithMany()
                        .HasForeignKey("AirNotificationChannelId");

                    b.HasOne("Nino.Core.Entities.MentionRole", "AirNotificationRole")
                        .WithMany()
                        .HasForeignKey("AirNotificationRoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Nino.Core.Entities.User", "AirNotificationUser")
                        .WithMany()
                        .HasForeignKey("AirNotificationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Nino.Core.Entities.Group", "Group")
                        .WithMany("Projects")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nino.Core.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nino.Core.Entities.Channel", "ProjectChannel")
                        .WithMany()
                        .HasForeignKey("ProjectChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nino.Core.Entities.Channel", "ReleaseChannel")
                        .WithMany()
                        .HasForeignKey("ReleaseChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nino.Core.Entities.Channel", "UpdateChannel")
                        .WithMany()
                        .HasForeignKey("UpdateChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("Nino.Core.Entities.Alias", "Aliases", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("ProjectId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("TEXT")
                                .UseCollation("NOCASE");

                            b1.HasKey("Id");

                            b1.HasIndex("ProjectId");

                            b1.ToTable("Alias");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId");
                        });

                    b.OwnsMany("Nino.Core.Entities.Administrator", "Administrators", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("ProjectId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("ProjectId");

                            b1.HasIndex("UserId");

                            b1.ToTable("Projects_Administrators");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId");

                            b1.HasOne("Nino.Core.Entities.User", "User")
                                .WithMany()
                                .HasForeignKey("UserId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.Navigation("User");
                        });

                    b.OwnsMany("Nino.Core.Entities.Staff", "KeyStaff", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<bool>("IsPseudo")
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("ProjectId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("ProjectId");

                            b1.HasIndex("UserId");

                            b1.ToTable("Projects_KeyStaff");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId");

                            b1.HasOne("Nino.Core.Entities.User", "User")
                                .WithMany()
                                .HasForeignKey("UserId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.OwnsOne("Nino.Core.Entities.Role", "Role", b2 =>
                                {
                                    b2.Property<Guid>("StaffId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Abbreviation")
                                        .IsRequired()
                                        .HasMaxLength(16)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(32)
                                        .HasColumnType("TEXT");

                                    b2.Property<decimal>("Weight")
                                        .HasColumnType("TEXT");

                                    b2.HasKey("StaffId");

                                    b2.ToTable("Projects_KeyStaff");

                                    b2.WithOwner()
                                        .HasForeignKey("StaffId");
                                });

                            b1.Navigation("Role")
                                .IsRequired();

                            b1.Navigation("User");
                        });

                    b.Navigation("Administrators");

                    b.Navigation("AirNotificationChannel");

                    b.Navigation("AirNotificationRole");

                    b.Navigation("AirNotificationUser");

                    b.Navigation("Aliases");

                    b.Navigation("Group");

                    b.Navigation("KeyStaff");

                    b.Navigation("Owner");

                    b.Navigation("ProjectChannel");

                    b.Navigation("ReleaseChannel");

                    b.Navigation("UpdateChannel");
                });

            modelBuilder.Entity("Nino.Core.Entities.User", b =>
                {
                    b.HasOne("Nino.Core.Entities.Group", null)
                        .WithMany("Users")
                        .HasForeignKey("GroupId");
                });

            modelBuilder.Entity("Nino.Core.Entities.Group", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Nino.Core.Entities.Project", b =>
                {
                    b.Navigation("Episodes");

                    b.Navigation("Observers");
                });
#pragma warning restore 612, 618
        }
    }
}
