using ICU4N.Text;
using System.Collections.Frozen;
using System.Text.Json.Serialization;

namespace Localizer
{
    /// <summary>
    /// Definition of a localization table for strings
    /// </summary>
    internal class Localization
    {
        /// <summary>
        /// Mapping of lookup keys to values for singular strings
        /// </summary>
        /// <remarks>Can be used by both <see cref="Localizer.T(string, string, object[])"/> and <see cref="Localizer.T(string, string, Dictionary{string, object}, string)"/>.</remarks>
        [JsonIgnore]
        public required FrozenDictionary<string, string> Singular { get; init; }
        /// <summary>
        /// Mapping of lookup keys to a map of plural strings
        /// </summary>
        /// <remarks>Can only be used by <see cref="Localizer.T(string, string, Dictionary{string, object}, string)"/>.</remarks>
        [JsonIgnore]
        public required FrozenDictionary<string, Dictionary<string, string>> Plural { get; init; }
        /// <summary>
        /// Plural rules for this locale, generated by ICU4N.
        /// </summary>
        [JsonIgnore]
        public PluralRules? PluralRules { get; set; }

        [JsonPropertyName("singular")]
        public Dictionary<string, string> SerializationSingular
        {
            get => new(Singular);
            init => Singular = value.ToFrozenDictionary();
        }

        [JsonPropertyName("plural")]
        public Dictionary<string, Dictionary<string, string>> SerializationPlural
        {
            get => new(Plural);
            init => Plural = value.ToFrozenDictionary();
        }
    }
}
