// SPDX-License-Identifier: MPL-2.0

using System.Collections.Frozen;
using System.Text.Json;
using System.Text.Json.Serialization;
using ICU4N.Text;

namespace Nino.Localization;

/// <summary>
/// A localization table for strings
/// </summary>
internal sealed class Localization
{
    /// <summary>
    /// Mapping of lookup keys to values for singular strings
    /// </summary>
    /// <remarks>Can be used by both <see cref="Localizer.T(string, string, object[])"/> and <see cref="Localizer.T(string, string, Dictionary{string, object}, string)"/>.</remarks>
    [JsonIgnore]
    public FrozenDictionary<string, string> Singular { get; }

    /// <summary>
    /// Mapping of lookup keys to a map of plural strings
    /// </summary>
    /// <remarks>Can only be used by <see cref="Localizer.T(string, string, Dictionary{string, object}, string)"/>.</remarks>
    [JsonIgnore]
    public FrozenDictionary<string, Dictionary<string, string>> Plural { get; }

    /// <summary>
    /// Plural rules for this locale, generated by ICU4N.
    /// </summary>
    [JsonIgnore]
    public PluralRules PluralRules { get; }

    /// <summary>
    /// Construct the localization data
    /// </summary>
    /// <param name="content">Flat list of key-value pairs</param>
    /// <param name="pluralRules">Plural rules</param>
    internal Localization(IReadOnlyDictionary<string, string> content, PluralRules pluralRules)
    {
        content = content.Where(e => !string.IsNullOrEmpty(e.Value)).ToDictionary();
        
        PluralRules = pluralRules;
        Singular = content.Where(l => !l.Key.Contains('_')).ToFrozenDictionary();
        Plural = content.Where(l => l.Key.Contains('_')).Select(kvp =>
            {
                var partition = kvp.Key.LastIndexOf('_');
                return new { BaseKey = kvp.Key[..partition], Form = kvp.Key[(partition + 1)..], kvp.Value };
            }).GroupBy(x => x.BaseKey)
            .ToFrozenDictionary(
                g => g.Key,
                g => g.ToDictionary(x => x.Form, x => x.Value)
            );
    }
}
